services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8180:8180"
    environment:
      - PORT=8180
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    network_mode: host
    environment:
      - PORT=3100

  nginx:
    build: ./nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
