services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8080" # 외부 노출 안 하고 Nginx 통해서만 접근
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80" # 외부 노출 안 하고 Nginx 통해서만 접근

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
