services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: loan_reviews

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
