root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # main.go가 있는 디렉토리 지정
  cmd = "go build -o tmp/main.exe ./cmd/server"
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
